brotli: bump version
haikuports/haikuports pull request #10008
Opened 2024-01-20 21:08 UTC by kenmays

Tested on Haiku R1B4 x64.
- Passed all unit tests.
- brotli 1.1.0

2024-01-21 13:05 UTC, jmairboeck requested changes

2024-01-21 13:05 UTC, jmairboeck commented on app-arch/brotli/brotli-1.0.9.recipe
> -		"$developDir"
This should be replaced with `rm -r` instead (see #10004).

2024-02-08 14:42 UTC, korli commented
What's the purpose of keeping the recipe for 1.0.9?

2024-02-08 14:53 UTC, kenmays commented
@korli - Fallback for current packages until we migrate them.

2024-02-08 15:10 UTC, Begasus commented
Needs to be checked if SONAME change(?) doesn't brake existing installs.
```
~> inrecipe lib:libbrotlidec
/Opslag/haikuports/app-arch/brotli/brotli-1.0.9.recipe:32:      lib:libbrotlidec$secondaryArchSuffix = $libVersionCompat
/Opslag/haikuports/dev-qt/qt6-base/qt6_base-6.6.0.recipe:43:    lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/media-gfx/fontforge/fontforge-20230101.recipe:38:    lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/media-libs/gst_plugins_good/gst_plugins_good-1.22.0.recipe:28:       lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/media-libs/libjxl/libjxl-0.6.1.recipe:45:    lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/media-libs/libjxl/libjxl-0.9.0.recipe:45:    lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/media-libs/woff2/woff2-1.0.2.recipe:26:      lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/net-libs/libsoup/libsoup3-3.2.2.recipe:26:   lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/net-libs/webkit-gtk/webkit_gtk-2.40.0.recipe:39:     lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/net-misc/remmina/remmina-1.4.29.recipe:32:   lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/net-misc/wget2/wget2-2.1.0.recipe:41:        lib:libbrotlidec$secondaryArchSuffix
/Opslag/haikuports/www-client/epiphany/epiphany-43.1.recipe:39: lib:libbrotlidec$secondaryArchSuffix
```

2024-02-08 17:15 UTC, kenmays commented
To minimize API/ABI crossover with callbacks, I can help migrate dependencies to the newer libs once merged.

2024-02-08 21:11 UTC, korli commented
> @korli - Fallback for current packages until we migrate them.

There is no fallback if the recipe names are identical. Why would there be any packages to migrate?

2024-02-16 08:30 UTC, merged