mesa: Added 24.2.0
haikuports/haikuports pull request #10852
Opened 2024-08-19 00:12 UTC by kenmays

2024-08-19 17:50 UTC, waddlesplash commented
CC @X547

2024-08-21 15:10 UTC, X547 requested changes

2024-08-21 15:10 UTC, X547 commented on sys-libs/mesa/mesa-24.2.0.recipe
> +	mako_python310
`pyyaml_python310` is missing.

2024-08-22 02:46 UTC, kenmays commented on sys-libs/mesa/mesa-24.2.0.recipe
> +	mako_python310
Fixef

2024-09-05 23:56 UTC, X547 commented
What is stopping from merging this?

2024-09-06 01:18 UTC, waddlesplash commented on sys-libs/mesa/mesa-24.2.1.recipe
> +#	sed -i "s/\/packages\/mesa-.*\/.self\/lib\/libvulkan_lvp.so/.\/libvulkan_lvp.so/" $addOnsDir/vulkan/icd.d/lvp_icd.x86_64.json
What's going on here?

2024-10-30 21:32 UTC, kenmays commented
@x547 - Closing. Can migrate once DRM ioctl is reworked for R1.

2024-10-30 21:32 UTC, closed without merging