Add rocksdb 9.6.1
haikuports/haikuports pull request #11177
Opened 2024-09-30 17:29 UTC by mtl1979

2024-10-01 05:18 UTC, humdingerb commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +SUMMARY="Embeddable persistent key-value store for fast storage"
```suggestion
SUMMARY="A persistent key-value store for fast storage"
```

2024-10-01 05:18 UTC, humdingerb commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +DESCRIPTION="Key-value store"
```suggestion
DESCRIPTION="RocksDB is an embeddable persistent key-value store for fast storage.

* Uses a log structured database engine, written entirely in C++, for \
maximum performance. Keys and values are just arbitrarily-sized byte streams.
* Is optimized for fast, low latency storage such as flash drives and \
high-speed disk drives. RocksDB exploits the full potential of high read/write \
rates offered by flash or RAM.
* Is adaptable to different workloads.
* Provides basic operations such as opening and closing a database, reading \
and writing to more advanced operations such as merging and compaction filters."
```

2024-10-21 07:55 UTC, Begasus requested changes

2024-10-21 07:55 UTC, Begasus commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +    "
Looks like there are spaces used here instead of one tab?

2024-10-21 09:30 UTC, mtl1979 commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +    "
Fixed.

2024-10-21 09:43 UTC, Begasus approved these changes

2024-10-21 09:44 UTC, merged

2024-10-21 16:11 UTC, jmairboeck commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +		$binDir
`$binDir` should be replaced with `$prefix/bin` (or `$commandBinDir` after defining that) so that this matches the PROVIDES above. Otherwise, the binaries are suffixed with `-x86` on x86 because it is a secondary architecture.

But it looks like the build failed anyway on x86: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/6972/builds/84614.log

2024-10-21 16:37 UTC, Begasus commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +		$binDir
@mtl1979 is there a fix to the error? If not maybe disable 32bit all together then.

2024-10-21 16:42 UTC, mtl1979 commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +		$binDir
@Begasus There is a fix, but it's not merged upstream yet... I can try the fix after downloading 32-bit ISO of Haiku...

2024-10-21 18:40 UTC, mtl1979 commented on dev-libs/rocksdb/rocksdb-9.6.1.recipe
> +		$binDir
See #11239.