Update hikounomizu to 1.1
haikuports/haikuports pull request #11184
Opened 2024-10-03 17:44 UTC by hnm-duncan

Update of the `games-arcade/hikounomizu` recipe to version 1.1.
It has no major changes except the dropping of GLU and the addition of enet.

Also moved the binary in its own `HikouNoMizu` subdirectory since it now also includes a server binary.

2024-10-21 07:50 UTC, Begasus requested changes

2024-10-21 07:50 UTC, Begasus commented on games-arcade/hikounomizu/hikounomizu-1.1.recipe
> +Currently, three characters are playable: Hikou, Takino and Hana."
Since you are sorting DESCRIPTION, lines can go up to 100 characters (I'm guessing you kept the 80 char limit).

2024-10-21 07:50 UTC, Begasus commented on games-arcade/hikounomizu/hikounomizu-1.1.recipe
> +SOURCE_URI="https://download.tuxfamily.org/hnm/1.1/hikounomizu-1.1-src-withdata.tar.bz2"
Use $portVersion string here:
```suggestion
SOURCE_URI="https://download.tuxfamily.org/hnm/$portVersion/hikounomizu-$portVersion-src-withdata.tar.bz2"
```

2024-10-21 15:49 UTC, hnm-duncan commented on games-arcade/hikounomizu/hikounomizu-1.1.recipe
> +		-DCMAKE_INSTALL_BINDIR=$appsDir/HikouNoMizu \
Thanks for the review! The server binary is now going to $prefix/bin and is also listed in PROVIDES.

2024-11-02 10:45 UTC, Begasus approved these changes

2024-11-02 10:45 UTC, merged

2024-11-02 10:45 UTC, Begasus commented
Thanks!