cppfront : add missing headers
haikuports/haikuports pull request #11206
Opened 2024-10-10 09:17 UTC by yann64

Headers inclusion is missing from original recipe.

2024-10-10 09:29 UTC, jmairboeck requested changes

2024-10-10 09:29 UTC, jmairboeck commented on dev-lang/cppfront/cppfront-0.7.4.recipe
> +	cp cppfront $binDir
This was correct before. `$binDir` includes the secondaryArch subdir on secondary architectures (i.e. x86), which is not wanted here.

2024-10-10 09:29 UTC, jmairboeck commented on dev-lang/cppfront/cppfront-0.7.4.recipe
> +	cp source/* $includeDir/cppfront/
Shouldn't this just copy the headers and not everything?

2024-10-16 16:46 UTC, Begasus commented
@jmairboeck good to go?

2024-10-16 16:54 UTC, jmairboeck commented
I didn't test it yet, but I think so.

2024-10-16 17:01 UTC, Begasus commented
OK, I'll leave it alone for now then, for the LGTM (untested also) :)

2024-10-16 20:26 UTC, yann64 commented
Hi sorry for the tardiness.
I won't be getting close to my Haiku machine before weekend at best so do not expect me updating the PR before. Sorry again 😐

2024-10-16 20:29 UTC, yann64 commented
I will need to check if copying only *.h into headers directory  (instead of everything) is ok to compile generated CPP code.

2024-10-17 18:24 UTC, yann64 reviewed
Corrected include path.
Tested generated package to compile sample source code. All works OK now.

2024-10-20 10:21 UTC, jmairboeck approved these changes

2024-10-20 12:09 UTC, merged