crunch: new recipe
haikuports/haikuports pull request #11328
Opened 2024-11-12 15:12 UTC by jsteinaker

A wordlist generator.
Not sure about the ARCHITECTURES, should I disable x86_gcc2 and enable x86 in SECONDARY_ARCHITECTURES? This should compile with every compiler under the sun.

2024-11-13 17:54 UTC, jmairboeck commented
If it builds without patching gcc2, I think this is fine. No need to make the recipe more complicated than it needs to be.

2024-11-22 00:50 UTC, jsteinaker commented
Thanks for testing @Begasus. I guess commandSuffix it's not needed since we're not building for x86_gcc2 anyway?

2024-11-22 06:28 UTC, Begasus commented on app-misc/crunch/crunch-3.6.recipe
> +	cmd:crunch$secondaryArchSuffix
For your latest comment, no commandSuffix needed, but also no $secondaryArchSuffix, the binary will be installed in $prefix/bin, so:
```suggestion
	cmd:crunch
```

2024-11-22 07:06 UTC, Begasus requested changes

2024-11-22 07:06 UTC, Begasus commented on app-misc/crunch/crunch-3.6.recipe
> +	haiku
Haiku should also be secondary architecture :)

```suggestion
	haiku$secondaryArchSuffix
```

2024-11-22 07:06 UTC, Begasus commented on app-misc/crunch/crunch-3.6.recipe
> +	haiku_devel
```suggestion
	haiku${secondaryArchSuffix}_devel
```

2024-11-22 07:08 UTC, Begasus commented on app-misc/crunch/crunch-3.6.recipe
> +	haiku_devel
Actually haiku${secondaryArchSuffix}_devel should go to BUILD_REQUIRES instead of BUILD_PREREQUIRES. :)

2024-11-23 06:37 UTC, Begasus approved these changes

2024-11-23 06:38 UTC, merged

2024-11-23 06:39 UTC, Begasus commented
Thanks!