IMUtils: new recipe
haikuports/haikuports pull request #5468
Opened 2020-12-04 16:42 UTC by extrowerk

2020-12-12 07:07 UTC, Begasus requested changes

2020-12-12 07:07 UTC, Begasus commented on dev-python/imutils/imutils-0.5.3.recipe
> +	cmd:cython$pythonVersion\n\
Same thing here as for numpy:
```diff
- 	cmd:cython$pythonVersion\n\
+ 	cmd:cython$pythonVersion$secondaryArchSuffix\n\
```

2020-12-12 07:07 UTC, Begasus commented on dev-python/imutils/imutils-0.5.3.recipe
> +	cmd:cython$pythonVersion
```diff
- 	cmd:cython$pythonVersion
+ 	cmd:cython$pythonVersion$secondaryArchSuffix
```

2020-12-12 07:07 UTC, Begasus commented on dev-python/imutils/imutils-0.5.3.recipe
> +		mv $binDir/range-detector $binDir/range_detector$pythonVersion
binary is installed in $prefix/bin so:
```diff
- 		mv $binDir/range-detector $binDir/range_detector$pythonVersion
+ 		mv $prefix/bin/range-detector $prefix/bin/range_detector$pythonVersion
```

2020-12-13 16:37 UTC, korli commented
Looks like a stale project (no commit for a year despite a pile of pull requests), not widely available:
https://repology.org/project/python:imutils/versions

2021-01-04 17:06 UTC, extrowerk commented
@Begasus: thanks, fixed.
@korli: i know, still it is used by some opencv related projects.

2021-01-13 06:24 UTC, merged