libmypaint: new recipe
haikuports/haikuports pull request #5935
Opened 2021-05-19 07:41 UTC by wattoc

2021-05-19 08:05 UTC, wattoc commented
Build server does not like the ISC licence?

2021-05-19 11:41 UTC, wattoc commented
Still WIP

2021-05-22 09:41 UTC, Begasus requested changes
Some changes needed for 32bit

2021-05-22 09:41 UTC, Begasus commented on media-libs/libmypaint/libmypaint-1.6.1.recipe
> +SECONDARY_ARCHITECTURES="?x86"
Doesn't build with gcc2 (no libjson_c there), builds ok with gcc8
```diff
-ARCHITECTURES="?x86_gcc2 ?x86 x86_64"
-SECONDARY_ARCHITECTURES="?x86"
+ARCHITECTURES="!x86_gcc2 x86_64"
+SECONDARY_ARCHITECTURES="x86"
```

2021-05-22 09:41 UTC, Begasus commented on media-libs/libmypaint/libmypaint-1.6.1.recipe
> +	cmd:python
python2.7 is deprecated, use python3.7 (or higher)
```diff
- 	cmd:python
+ 	cmd:python3.7
```

2021-05-22 09:41 UTC, Begasus commented on media-libs/libmypaint/libmypaint-1.6.1.recipe
> +	cmd:intltool_update$secondaryArchSuffix
No secondaryArchSuffix needed here:
```diff
- 	cmd:intltool_update$secondaryArchSuffix
+ 	cmd:intltool_update
```

2021-05-24 07:39 UTC, Begasus approved these changes

2021-05-24 07:39 UTC, Begasus commented
Thanks! :+1:

2021-05-24 07:39 UTC, merged