Added zbar recipe, first revision.
haikuports/haikuports pull request #6344
Opened 2021-10-30 15:25 UTC by barctor

Adds a recipe for [zbar](http://zbar.sourceforge.net/) providing:
* Main package: cmd:zbarimg - command line program to scan QR codes & barcodes in image files
* Devel package: lib:libzbar - C library/headers exposing API to scan barcodes & QR codes

Currently builds package without GTK, QT, or Python support.

2021-10-31 06:42 UTC, extrowerk commented
Not tested, but looks good.

2021-10-31 06:54 UTC, Begasus commented
Latest release is 0.23.90 according to repology: https://repology.org/project/zbar/versions
Hosted at: https://github.com/mchehab/zbar/

2021-10-31 12:07 UTC, barctor commented
Thanks @Begasus I didn't know development had moved to github.
I've amended the commit to use the latest release from the linked git repo.
As far as tests go:
* Main package: zbarimg is able to scan images and print any QR code data found
* Devel package: i can build a project that references zbar.h but have yet to test the actual API to see if it works as intended

2021-10-31 17:51 UTC, Begasus requested changes

2021-10-31 17:51 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +fi
libVersion comes after commandSuffix: see https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines#ordering

2021-10-31 17:51 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +	lib:libintl$secondaryArchSuffix
Sort alphabetically (also in BUILD_REQUIRES)

2021-10-31 17:51 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +	haiku${secondaryArchSuffix}_devel
Changes:
```diff
- 	imagemagick${secondaryArchSuffix}_devel (not needed)
+	haiku${secondaryArchSuffix}_devel
	devel:libMagick++_7.Q16HDRI$secondaryArchSuffix
	devel:libMagickCore_7.Q16HDRI$secondaryArchSuffix
	devel:libMagickWand_7.Q16HDRI$secondaryArchSuffix
	devel:libiconv$secondaryArchSuffix
	devel:libjpeg$secondaryArchSuffix
	devel:libintl$secondaryArchSuffix
-	haiku${secondaryArchSuffix}_devel
```

2021-10-31 17:51 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +	cmd:libtool
Change for secondary architecture:
```diff
- 	cmd:libtool
+ 	cmd:libtoolize$secondaryArchSuffix
```

2021-10-31 17:51 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +	LDFLAGS="-lintl" runConfigure ./configure \
We need to move the binary to $prefix/bin here too:
```diff
- 	LDFLAGS="-lintl" runConfigure ./configure \
+ 	LDFLAGS="-lintl" runConfigure --omit-dirs binDir ./configure \
+ 	 	--bindir=$commandBinDir \

2021-10-31 19:17 UTC, barctor commented
Thanks for the review @Begasus 
I think I have addressed all the issues you found in the recipe.
I'll also make sure I read through the guide more thoroughly before submitting another recipe :)

2021-11-01 08:02 UTC, Begasus commented on media-gfx/zbar/zbar-0.23.90.recipe
> +
No new line between PROVIDES_devel and REQUIRES_devel
```diff
-
```

2021-11-01 18:16 UTC, barctor commented
Sorted the PROVIDES_devel and REQUIRES_devel spacing, and removed the extra space between libVersion and PROVIDES

2021-11-01 18:29 UTC, Begasus approved these changes

2021-11-01 18:29 UTC, merged

2021-11-01 18:40 UTC, Begasus commented
Thanks! :+1: