libdrm: add recipe
haikuports/haikuports pull request #6467
Opened 2021-12-09 04:54 UTC by kenmays

2021-12-09 07:05 UTC, extrowerk commented on sys-libs/libdrm/libdrm-2.4.109.recipe
> +SOURCE_DIR="libdrm-${portVersion}"
necessary?

2021-12-09 07:06 UTC, extrowerk commented on sys-libs/libdrm/libdrm-2.4.109.recipe
> +	lib:libdrm_nouveau$secondaryArchSuffix = 2.0.0
but the meson invocation says: "-Dnouveau=false -Dintel=false "

2021-12-09 07:15 UTC, extrowerk commented on sys-libs/libdrm/libdrm-2.4.109.recipe
> +#	appVersion=${portVersion//\./ }
remove if unneeded

2021-12-09 13:59 UTC, waddlesplash requested changes
As far as I'm aware, @X547's work uses a totally separate implementation of libdrm, not this one.

2021-12-09 22:49 UTC, X547 commented
I use original libdrm_amdgpu and libdrm headers, but libdrm.so code is different.

2022-02-05 19:35 UTC, kenmays commented
Using libdrm2 framework instead.

2022-02-05 19:35 UTC, closed without merging