Add recipe for reportlab 3.6.9
haikuports/haikuports pull request #6825
Opened 2022-04-11 17:50 UTC by ivanholmes

2022-04-11 18:08 UTC, ivanholmes commented
Just noticed I have submitted this without filling the description properly! I will sort it shortly.
Sorry for the noise

2022-04-11 18:32 UTC, ivanholmes commented
Description now sorted

2022-04-13 12:42 UTC, extrowerk commented on dev-python/reportlab/patches/reportlab-3.6.9.patchset
> ++        	aDir(I, "/boot/system/develop/headers/freetype2")
Python3 is only available for secondary arch on x86, but as your include folder order is primary-arch then secondary-arch it is possible the compiler will find the wrong set of headers.
This is also true for the libs.

I would propose to flip the folder order.

2022-04-13 12:57 UTC, ivanholmes commented on dev-python/reportlab/patches/reportlab-3.6.9.patchset
> ++        	aDir(I, "/boot/system/develop/headers/freetype2")
Done, thanks

2022-04-15 09:46 UTC, Begasus requested changes
libfreetype is linked in and I think it's needed for the subpackages as a requirement

2022-04-15 09:46 UTC, Begasus commented on dev-python/reportlab/reportlab-3.6.9.recipe
> +	lib:libfreetype$secondaryArchSuffix
```diff
- 	lib:libfreetype$secondaryArchSuffix
```

2022-04-15 09:46 UTC, Begasus commented on dev-python/reportlab/reportlab-3.6.9.recipe
> +	haiku\n\
```diff
+ 	lib:libfreetype$secondaryArchSuffix\n\
```

2022-04-15 09:46 UTC, Begasus commented on dev-python/reportlab/reportlab-3.6.9.recipe
> +	haiku\n\
```diff
+ 	lib:libfreetype$secondaryArchSuffix\n\
```

2022-04-15 12:06 UTC, ivanholmes commented
I agree, I'm away from my Haiku machine for the weekend but will push this change upon my return


________________________________
De : Schrijvers Luc ***@***.***>
Envoyé : vendredi 15 avril 2022 10:47
À : haikuports/haikuports
Cc: Ivan Holmes; Author
Objet : Re: [haikuports/haikuports] Add recipe for reportlab 3.6.9 (PR #6825)

@Begasus requested changes on this pull request.

libfreetype is linked in and I think it's needed for the subpackages as a requirement

________________________________

In dev-python/reportlab/reportlab-3.6.9.recipe:

> +REVISION="1" 
+pypi="81ff7e3f9fd345cd4685f964fbc3d89a06f39a4f552ab1c2a5769a0f9013" 
+SOURCE_URI="https://files.pythonhosted.org/packages/16/31/$pypi/reportlab-$portVersion.tar.gz" 
+CHECKSUM_SHA256="5d0cc3682456ad213150f6dbffe7d47eab737d809e517c316103376be548fb84" 
+SOURCE_DIR="reportlab-$portVersion" 
+PATCHES="reportlab-$portVersion.patchset" 
+ 
+ARCHITECTURES="all !x86_gcc2" 
+SECONDARY_ARCHITECTURES="x86" 
+ 
+PROVIDES=" 
+ $portName = $portVersion 
+ " 
+REQUIRES=" 
+ haiku$secondaryArchSuffix 
+ lib:libfreetype$secondaryArchSuffix 

-  lib:libfreetype$secondaryArchSuffix

________________________________

In dev-python/reportlab/reportlab-3.6.9.recipe:

> + " 
+BUILD_PREREQUIRES=" 
+ cmd:gcc$secondaryArchSuffix 
+ cmd:git 
+ " 
+ 
+PYTHON_PACKAGES=(python3 python38 python39 python310) 
+PYTHON_VERSIONS=(3.7 3.8 3.9 3.10) 
+for i in "${!PYTHON_PACKAGES[@]}"; do 
+pythonPackage=${PYTHON_PACKAGES[i]} 
+pythonVersion=${PYTHON_VERSIONS[$i]} 
+eval "PROVIDES_${pythonPackage}=\"\ 
+ ${portName}_$pythonPackage = $portVersion\ 
+ \"; \ 
+REQUIRES_$pythonPackage=\"\ 
+ haiku\n\ 

+  lib:libfreetype$secondaryArchSuffix\n\

________________________________

In dev-python/reportlab/reportlab-3.6.9.recipe:

> + " 
+BUILD_PREREQUIRES=" 
+ cmd:gcc$secondaryArchSuffix 
+ cmd:git 
+ " 
+ 
+PYTHON_PACKAGES=(python3 python38 python39 python310) 
+PYTHON_VERSIONS=(3.7 3.8 3.9 3.10) 
+for i in "${!PYTHON_PACKAGES[@]}"; do 
+pythonPackage=${PYTHON_PACKAGES[i]} 
+pythonVersion=${PYTHON_VERSIONS[$i]} 
+eval "PROVIDES_${pythonPackage}=\"\ 
+ ${portName}_$pythonPackage = $portVersion\ 
+ \"; \ 
+REQUIRES_$pythonPackage=\"\ 
+ haiku\n\ 

+  lib:libfreetype$secondaryArchSuffix\n\

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-19 12:49 UTC, Begasus approved these changes

2022-04-19 12:50 UTC, merged

2022-04-19 12:50 UTC, Begasus commented
Thanks! Keep an eye on the buildmaster for this :)

2022-04-19 14:25 UTC, ivanholmes commented
> Thanks! Keep an eye on the buildmaster for this :)

Brilliant thanks for your assistance