Add Bugdom 1.3.1
haikuports/haikuports pull request #6897
Opened 2022-05-08 19:18 UTC by ivanholmes

Based on #6891

2022-05-09 00:54 UTC, ivanholmes commented
Ready to merge from my POV.

2022-05-10 08:05 UTC, korli commented on games-action/bugdom/bugdom-1.3.1.recipe
> +PATCHES_2="bugdom-$portVersion-source2.patchset"
```suggestion
SOURCE_URI="https://github.com/jorio/Bugdom/archive/refs/tags/$portVersion.tar.gz"
CHECKSUM_SHA256="64f266f7f749d9346b1202fdd191a0e445f6bb90372e32c7250b4fb679150523"
SOURCE_DIR="Bugdom-$portVersion"
PATCHES="bugdom-$portVersion.patchset"
srcGitRev2="b9ddab06cdc0b9e4a8085e50974213b6c9625436"
SOURCE_URI_2="https://github.com/jorio/Pomme/archive/$srcGitRev2.tar.gz"
CHECKSUM_SHA256_2="96be755cbbcc2f4a3677dd4388599bad4b5cc771a55d927bb8ebe646d7142b52"
SOURCE_FILENAME_2="Pomme-$srcGitRev2.tar.gz"
SOURCE_DIR_2="Pomme-$srcGitRev2"
PATCHES_2="bugdom-$portVersion-source2.patchset"
ADDITIONAL_FILES="bugdom.rdef.in"
```

2022-05-10 08:05 UTC, korli commented on games-action/bugdom/bugdom-1.3.1.recipe
> +	lib:libgl$secondaryArchSuffix
```suggestion
	lib:libgl$secondaryArchSuffix
	lib:libsdl2_2.0$secondaryArchSuffix
```

2022-05-10 08:05 UTC, korli commented on games-action/bugdom/bugdom-1.3.1.recipe
> +	devel:libgl$secondaryArchSuffix
```suggestion
	devel:libgl$secondaryArchSuffix
	devel:libsdl2_2.0$secondaryArchSuffix
```

2022-05-10 08:05 UTC, korli commented on games-action/bugdom/bugdom-1.3.1.recipe
> +	cmd:gcc$secondaryArchSuffix
```suggestion
	cmd:gcc$secondaryArchSuffix
	cmd:make
```

2022-05-11 23:56 UTC, augiedoggie requested changes

2022-05-11 23:56 UTC, augiedoggie commented on games-action/bugdom/additional-files/bugdom.rdef.in
> +	minor  = 0,
The template rdef.in file you started with doesn't seem to be using the MINOR part of the version.

2022-05-11 23:56 UTC, augiedoggie commented on games-action/bugdom/additional-files/bugdom.rdef.in
> +resource app_flags B_MULTIPLE_LAUNCH;
```suggestion
resource app_flags B_EXCLUSIVE_LAUNCH | B_ARGV_ONLY;
```

2022-05-12 00:57 UTC, augiedoggie requested changes

2022-05-12 00:57 UTC, augiedoggie commented on games-action/bugdom/bugdom-1.3.1.recipe
> +	local MIDDLE="`echo "$portVersion" | cut -d. -f2`"
```suggestion
	local MIDDLE="`echo "$portVersion" | cut -d. -f2`"
	local MINOR="`echo "$portVersion" | cut -d. -f3`"
```

2022-05-12 00:57 UTC, augiedoggie commented on games-action/bugdom/bugdom-1.3.1.recipe
> +		-e "s|@MIDDLE@|$MIDDLE|" \
```suggestion
		-e "s|@MIDDLE@|$MIDDLE|" \
		-e "s|@MINOR@|$MINOR|" \
```

2022-05-12 00:59 UTC, ivanholmes commented on games-action/bugdom/bugdom-1.3.1.recipe
> +	local MIDDLE="`echo "$portVersion" | cut -d. -f2`"
Oops, will fix for the others too

2022-05-12 01:09 UTC, merged