Update openttd, openttd_gfx, openttd_sfx, openttd_msx
haikuports/haikuports pull request #7052
Opened 2022-07-13 02:00 UTC by Thanson16

Update openttd and its asset packages to the latest version. Upstream
development switched to a new CDN and changed their build system to
CMake, so changes are somewhat more significant than just a version
bump.

Briefly tested and basic functionality seems to work. Saving/loading
games works. Downloading content through their system also works.
Did not confirm whether network play works, although I'm able to browse
the server list.

I considered fiddling with getting their SDL2 build working, but the SDL1
build seems fully functional and upstream supports both so I decided to
stop here and see if anyone here had feedback on whether that is even
desirable.

I've only been using Haiku for a week or so and this is my first time
working with the packaging system, so I look forward to feedback on
whether I'm doing it right.

Awesome project, everyone!

2022-07-13 04:53 UTC, Begasus requested changes

2022-07-13 04:53 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
> +	lib:libgl$secondaryArchSuffix
A few changes, first one is a leftover probably (cosmetic):
```diff
-	lib:libsdl$secondaryArchSuffix
+	lib:libSDL_1.2$secondaryArchSuffix
	lib:libz$secondaryArchSuffix
-	lib:libgl$secondaryArchSuffix
+	lib:libGL$secondaryArchSuffix
```
For libSDL also in devel:
Sort alphabetically

2022-07-13 04:53 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
> +
Could be simplified:
```diff
-	mkdir -p build ; cd build
-	cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-	-DCMAKE_INSTALL_PREFIX=$prefix \
-	-DCMAKE_INSTALL_DATADIR=$dataDir \
-	-DCMAKE_INSTALL_BINDIR=$appsDir \
-	-DCMAKE_INSTALL_DOCDIR=$docDir \
-	-DCMAKE_INSTALL_MANDIR=$manDir
+	cmake -B buid -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+	$cmakeDirArgs \
+	-DCMAKE_INSTALL_BINDIR=$appsDir
```
Changes for make further also

2022-07-13 04:53 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
>  	make $jobArgs
```diff
-	make $jobArgs
+	make -C build $jobArgs
```

2022-07-13 04:53 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
> +	cd build
```diff
- 	cd build
```

2022-07-13 04:53 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
>  	make install
```diff
- 	make install
+ 	make -C build install
```

2022-07-13 04:54 UTC, Begasus commented
Made some suggestions, first of all, as a short Haiku user thanks on the work you did here.
Need to confirm the build and install here before we merge.

2022-07-13 05:56 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
>  REVISION="2"
Forgot one :)
As this is a new version REVISION is reset to 1
```diff
- REVISION="2"
+ REVISION="1"
```

2022-07-13 08:22 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
>  	export includeDir=/system/$relativeIncludeDir
Not needed:
```diff
- 	export includeDir=/system/$relativeIncludeDir
```

2022-07-13 08:22 UTC, Begasus commented on games-simulation/openttd/openttd-12.2.recipe
> +	rm -r $prefix/share
Change to:
```diff
- 	rm -r $prefix/share
+ 	rm -r $dataDir/{applications,icons,pixmaps}
```

2022-07-13 08:43 UTC, Begasus reviewed
After cleaning the build these files will be deleted anyhow.

2022-07-13 08:43 UTC, Begasus commented on games-simulation/openttd_gfx/openttd_gfx-7.1.recipe
> +	rm opengfx-$portVersion-all.zip
Not needed:
```diff
- 	rm opengfx-$portVersion-all.zip
```

2022-07-13 08:43 UTC, Begasus commented on games-simulation/openttd_msx/openttd_msx-0.4.2.recipe
> +	rm openmsx-$portVersion-all.zip
Not needed:
```diff
- 	rm openmsx-$portVersion-all.zip
```

2022-07-13 08:43 UTC, Begasus commented on games-simulation/openttd_sfx/openttd_sfx-1.0.3.recipe
> +	rm opensfx-$portVersion-all.zip
Not needed:
```diff
- 	rm opensfx-$portVersion-all.zip
```

2022-07-13 08:43 UTC, Begasus commented
Think that should cover it, the changes are mostly cosmetic and more in line of the current format.

2022-07-13 08:51 UTC, Begasus commented
Here the sounds provided by `openttd_msx` don't seem to be loaded, in the settings window they don't show up either, previous version does load and is mentioned in the settings window?

2022-07-22 15:23 UTC, merged

2022-07-25 01:40 UTC, Thanson16 commented
Hi, sorry that I haven't been active the last few days. I didn't actually finish getting all your suggested fixes done before the PR was merged. I will attempt to get a new PR with the music-not-loading fix in sometime into he next week, since I think that was the only outstanding suggestion that affected functionality.

Thank you for your helpful suggestions and for your timely response.

2022-07-25 08:08 UTC, Begasus commented
No problem, once you get around to it I'll be sure to check it out :)