cldr-emoji-annotation: new recipe
haikuports/haikuports pull request #7364
Opened 2022-11-03 09:22 UTC by pengphei

Signed-off-by: Han Pengfei <pengphei@qq.com>

2022-11-05 10:12 UTC, Begasus requested changes

2022-11-05 10:12 UTC, Begasus commented on app-i18n/cldr-emoji-annotation/cldr_emoji_annotation-37.0_13.0_0_2.recipe
> +SECONDARY_ARCHITECTURES="x86"
No need for SECONDARY_ARCHITECTURES

2022-11-05 10:12 UTC, Begasus commented on app-i18n/cldr-emoji-annotation/cldr_emoji_annotation-37.0_13.0_0_2.recipe
> +	./autogen.sh
autogen.sh calls for aclocal, autoheader, autoconf and automake, it also calls configure, so maybe just drop autogen.sh here and run autoreconf -vfi ?

2022-11-10 05:50 UTC, korli commented
Why use this package? From the README: 
> I decided to use tarballs in https://github.com/unicode-org/cldr/releases
directly and this repo is no longer maintained.

2022-11-10 06:20 UTC, pengphei commented
> Why use this package? From the README:
> 
> > I decided to use tarballs in https://github.com/unicode-org/cldr/releases
> > directly and this repo is no longer maintained.

hmmm, I have checked opensuse, which uses cldr-emoji-annotation instead of unicode-cldr.

https://build.opensuse.org/package/show/M17N/cldr-emoji-annotation.

well, gentoo use unicode-cldr.

https://github.com/gentoo/gentoo/tree/master/app-i18n/unicode-cldr

I haven't figured out they provide the same thing ;(

2022-11-11 00:41 UTC, closed without merging