gutenprint: bumped for R1B4
haikuports/haikuports pull request #7381
Opened 2022-11-07 15:26 UTC by kenmays

2022-11-08 17:05 UTC, waddlesplash commented on net-print/gutenprint/gutenprint9-5.3.4.recipe
> +SOURCE_URI="https://github.com/echiu64/gutenprint/archive/$SrcGitRev.tar.gz"
This is an unofficial mirror. It should not be used as a source in HaikuPorts.

2022-11-08 19:28 UTC, waddlesplash commented
We should not be using a mirror at all.

2022-11-08 20:07 UTC, kenmays commented
Official repo - core/main developer (see: QMPlay2).

2022-11-08 21:57 UTC, waddlesplash commented
It's still a mirror. We should use the sources from the official site.

2022-11-09 04:40 UTC, waddlesplash commented
... we should not be using a snapshot build either, and I'm not sure those have stable SHAsums. We should just use the actual release!

2022-11-09 05:30 UTC, korli commented
We already use the release 5.3.4 for gutenprint9. What's the point of this PR?

2022-11-09 06:58 UTC, kenmays commented
Ok. Closing.

2022-11-09 19:32 UTC, kenmays commented
Note: We didn't migrate haiku-core to gutenprint9 yet - as of hrev56588.

2022-11-09 19:39 UTC, kenmays commented
@korli - This PR includes commits fixing bug issues with libusb 1.0.26

2022-11-10 05:41 UTC, korli commented
> @korli - This PR includes commits fixing bug issues with libusb 1.0.26

Have you references for these? You can eventually download patches from github, for instance, https://github.com/echiu64/gutenprint/commit/c64d30b9f93dff5d46134d6cb45af177ab1639e4.patch

2022-11-10 05:43 UTC, korli commented on net-print/gutenprint/gutenprint9-5.3.4.recipe
> +	autogen.sh --without-cups --with-doc=no --disable-static \
autogen.sh isn't needed on release tarballs.

2022-11-10 07:23 UTC, kenmays commented on net-print/gutenprint/gutenprint9-5.3.4.recipe
> +	autogen.sh --without-cups --with-doc=no --disable-static \
Resolved.

2022-11-10 09:01 UTC, korli requested changes
Please use a release tarball and a source URL for the patch. Please focus on the bug this PR is supposed to fix, otherwise you can directly close this PR.

2022-11-10 09:33 UTC, kenmays commented
The source tarball is the same used by Debian and Ubuntu testing.

2022-11-10 10:07 UTC, korli commented
Please use a release tarball and a source URL for the patch. 

> The source tarball is the same used by Debian and Ubuntu testing.

It's still a snapshot.

2022-11-10 16:01 UTC, kenmays commented
I'll close for now. No critical patches observed.

2022-11-10 16:01 UTC, closed without merging