hex_a_hop: Add recipe
haikuports/haikuports pull request #8392
Opened 2023-04-14 19:46 UTC by win8linux

*Hex-a-Hop* is a hexagonal tile-based puzzle game wherein the player must eliminate all green tiles by walking on them. Limitless undos, no time limits, just get rid of the green tiles!  Different kinds of tiles are introduced as the player progresses further for variety.

Running on `x86_64`:
![screenshot1](https://user-images.githubusercontent.com/11584387/232141062-e9960a2c-3820-474a-aebb-38d7a3551def.png)
![screenshot3](https://user-images.githubusercontent.com/11584387/232141071-1b5d4795-9c5c-4dce-87e9-1d6fd9ce601c.png)
![screenshot5](https://user-images.githubusercontent.com/11584387/232141078-0c0f5302-6b29-4770-92d9-64a0c03a6217.png)
![screenshot6](https://user-images.githubusercontent.com/11584387/232141087-16c7e3ed-da15-421c-8d8f-0e628fcb84f8.png)

2023-04-14 19:51 UTC, win8linux commented
This is the first time I've encountered Autotools, so there may be some unnecessary build steps that need to be removed.

2023-04-16 15:07 UTC, Begasus requested changes

2023-04-16 15:07 UTC, Begasus commented on games-puzzle/hex_a_hop/hex_a_hop-1.1.0.recipe
> +SECONDARY_ARCHITECTURES="!x86"
OK for secondary architecture: 
```diff
-SECONDARY_ARCHITECTURES="!x86"
+SECONDARY_ARCHITECTURES="x86"
```

2023-04-16 15:07 UTC, Begasus commented on games-puzzle/hex_a_hop/hex_a_hop-1.1.0.recipe
> +	mkdir -p $appsDir
Not needed:
```diff
-	mkdir -p $appsDir
```

2023-04-16 16:09 UTC, win8linux reviewed
All requested changes have been made.

2023-04-16 16:17 UTC, humdingerb commented on games-puzzle/hex_a_hop/hex_a_hop-1.1.0.recipe
> +HOMEPAGE="http://hexahop.sourceforge.net"
```suggestion
HOMEPAGE="https://hexahop.sourceforge.net"
```

2023-04-16 16:23 UTC, Begasus commented on games-puzzle/hex_a_hop/hex_a_hop-1.1.0.recipe
> +	addAppDeskbarSymlink $appsDir/hex-a-hop "Hex-a-hop"
Nitpicking maybe :) (suggestion)
```
	mv $appsDir/hex-a-hop $appsDir/Hex-a-hop
	addAppDeskbarSymlink $appsDir/Hex-a-hop
```

2023-04-16 16:23 UTC, Begasus approved these changes

2023-04-16 16:25 UTC, Begasus commented
@humdingerb maybe you could bring your magic skills and create an icon? ;)

2023-04-16 16:31 UTC, Begasus commented
LGTM, if only we had an icon, but can be added later. Thanks @win8linux

2023-04-16 17:08 UTC, humdingerb approved these changes

2023-04-16 17:10 UTC, humdingerb commented
> @humdingerb maybe you could bring your magic skills and create an icon? ;)

I'm not that good an iconizer... we'd need @Handmaus for best results. 😃

2023-04-16 17:17 UTC, win8linux commented
Could just make an issue for an icon after the merge.

2023-04-16 17:22 UTC, humdingerb commented
> Could just make an issue for an icon after the merge.

Yes, and/or advertise on this thread:
https://discuss.haiku-os.org/t/missing-icons-rdef-hvif-iom

2023-04-16 17:26 UTC, win8linux commented
> Yes, and/or advertise on this thread:
> https://discuss.haiku-os.org/t/missing-icons-rdef-hvif-iom

Right, make the issue then post it on that thread. Got it.

2023-04-16 18:09 UTC, merged