Tuxpuck: add recipe
haikuports/haikuports pull request #9184
Opened 2023-08-11 19:04 UTC by Luca1991

Hi,
this is a recipe for Tuxpuck an opensource arcade game.
What's include:
* Tuxpuck source url 
* All the patches from the debian gaming team
* My patch to make it buildable on haiku

As this is the first time that I write a recipe for haiku, please give it a closer look before to merge, thanks :) 

Forum thread as a ref: https://discuss.haiku-os.org/t/i-ported-tuxpuck/13811

2023-08-11 19:38 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +	cmd:pkg_config
Needs secondaryArchSuffix also:
```diff
-	cmd:pkg_config
+	cmd:pkg_config$secondaryArchSuffix
```

2023-08-12 09:00 UTC, Begasus requested changes

2023-08-12 09:00 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +	addAppDeskbarSymlink $appsDir/tuxpuck
Maybe add the man page also?
```
	mkdir -p $appsDir $manDir/man6
	cp tuxpuck $appsDir/tuxpuck
	cp man/tuxpuck.6.gz $manDir/man6
	addAppDeskbarSymlink $appsDir/tuxpuck
```

2023-08-12 09:01 UTC, Begasus commented
Builds OK, launching is fine too, but had to kill it due to tuxpuck grabbing almost all the cores and RAM?

2023-08-12 12:40 UTC, Luca1991 commented
@Begasus I implemented your proposed fixes (thanks a lot and sorry for that).

Let me build it again on my haiku vm so I can tell you something about the CPU/RAM issue.

Thank you

2023-08-12 12:57 UTC, Luca1991 commented
@Begasus it seems that it doesn't grab a lot of RAM/CPU from my VM:

<img width="1108" alt="Screenshot 2023-08-12 alle 14 53 01" src="https://github.com/haikuports/haikuports/assets/3731220/cef2b693-07fd-4bdb-bfc3-8c0a44a3e60a">

<img width="1105" alt="Screenshot 2023-08-12 alle 14 53 20" src="https://github.com/haikuports/haikuports/assets/3731220/7a27fe6e-eb2a-41af-a0bb-d9a6c511e42f">

2023-08-12 18:02 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +
Sorry, missed this one :)
No empty line between BUILD_REQUIRES and BUILD_PREREQUIRES
```diff
-
```

2023-08-12 18:03 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +
Information about this can be found here: https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines

2023-08-12 18:43 UTC, Luca1991 commented
@Begasus fixed! Thank you for the link, I'll make sure to follow it the next time :)

2023-08-12 19:32 UTC, Begasus requested changes
2 Trailing whitespaces left.

2023-08-12 19:32 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +{
Trailing whitespace here
```diff
-{	
+{
```

2023-08-12 19:32 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +{
Same here:
```diff
-{	
+{
```

2023-08-12 19:50 UTC, Luca1991 commented
Oh sorry, I misunderstood your previous comment about the trailing whitespaces!
I think it is fixed now, please let me know.
Thanks.

2023-08-14 05:56 UTC, Begasus approved these changes

2023-08-14 05:59 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +	libpng-transition.patch
Missed one (whitespace) :)
```diff
-	libpng-transition.patch 
+	libpng-transition.patch
```

2023-08-14 07:44 UTC, Begasus commented on games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
> +	addAppDeskbarSymlink $appsDir/tuxpuck
Looks nicer :)
```diff
-	cp tuxpuck $appsDir/tuxpuck
+	cp tuxpuck $appsDir/TuxPuck
	cp man/tuxpuck.6.gz $manDir/man6
-	addAppDeskbarSymlink $appsDir/tuxpuck
+	addAppDeskbarSymlink $appsDir/TuxPuck
```

2023-08-14 10:05 UTC, Luca1991 commented
@Begasus I guess you are starting to hate me for those trailing whitespaces 😅

This time i have doublechecked each line to make sure no more trailing whitespaces are left (and changed tuxpuck to TuxPuck).

I hope this is ok now, thanks a lot for your patience, next time will be easier 😉

2023-08-14 10:46 UTC, Begasus commented
> @Begasus I guess you are starting to hate me for those trailing whitespaces 😅

No problem, doing this in between, seem to find something new everytime, last comment though, then I'll merge, thanks for your patience (PS checked again and running smooth now, not sure what caused it the other day).

2023-08-14 11:27 UTC, Luca1991 commented
It should be ok now, please give it another look and let me know. Thanks :)

2023-08-14 11:33 UTC, merged

2023-08-14 11:34 UTC, Begasus commented
Thanks! buildmasters are still pretty active atm, so it will take some time before they end up in the depot for install.