Flashback: add recipe
haikuports/haikuports pull request #9656
Opened 2023-10-20 20:48 UTC by Luca1991

This is a recipe for Flashback.
This is based on the opensource reimplementation called  REminiscence REinforced.
Launch script + icon included.

You need original game files to play (I tested the DOS version).

@Begasus  I didn't forget the issue with 32bit build of melonDS, it is just that I have a couple of recipes already  ready.

2023-10-21 05:40 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +2020-2021 Alex Chermenin"
1 tab in front of the line

2023-10-21 05:40 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +flashback.sh"
1 tab in front of this line too.

2023-10-21 07:52 UTC, Luca1991 commented
Proposed changes implemented ;)

2023-10-21 15:34 UTC, Begasus requested changes

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +the game 'Flashback: The Quest For Identity' made by Delphine Software and released in 1992.
Wrap lines up to 100 characters, cut line at the end with a backslash.

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +	tremor$secondaryArchSuffix
There is a library there :)
```diff
-	tremor$secondaryArchSuffix
```

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +	tremor$secondaryArchSuffix
Use 1 tab in front of the lines (several spaces in the recipe atm).

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +        lib:libSDL2_2.0$secondaryArchSuffix
Use tremors library:
```diff
+	lib:libvorbisidec$secondaryArchSuffix
```

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +	tremor${secondaryArchSuffix}_devel
Same here:
```diff
-	tremor${secondaryArchSuffix}_devel
```

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +	devel:libSDL2_2.0$secondaryArchSuffix
Here too:
```diff
+	devel:libvorbisidec$secondaryArchSuffix
```

2023-10-21 15:34 UTC, Begasus commented on games-action/flashback/flashback-0.5.2.recipe
> +	cp $portDir/additional-files/flashback.sh "$binDir/flashback"
Better copy this to `$prefix/bin`, doing this in `$bindir` ends up in `$prefix/bin/x86` on 32bit secondary architecture and then needs `cmd:flashback$secondaryArchSuffix` in PROVIDES then.

2023-10-21 18:20 UTC, Luca1991 commented
Proposed changes implemented

2023-10-24 08:11 UTC, Luca1991 commented
@Begasus is there anything else preventing the merge? Thanks

2023-10-25 05:49 UTC, Begasus commented
> @Begasus is there anything else preventing the merge? Thanks

Maybe also add the IOM file in here too?

2023-10-25 08:12 UTC, Luca1991 commented
@Begasus it is an SVG converted to HVIF. Is it possible to use an rdef to apply an icon to an sh script?

2023-10-25 09:10 UTC, Begasus commented
> @Begasus it is an SVG converted to HVIF. Is it possible to use an rdef to apply an icon to an sh script?

Maybe better export to rdef then, yes you can use rdef to apply the icon to a script, see:
https://github.com/Begasus/haikuports/wiki/Useful-variables-for-recipes#rename-rdef-to-rsrc-usefull-sometimes-for-scripts-that-cant-use-rdef-files

2023-10-25 11:51 UTC, Luca1991 commented
@Begasus now it should be ok.

2023-10-25 12:50 UTC, Begasus commented
Thanks, keep an eye out on the buildmasters for build progress :)

2023-10-25 12:50 UTC, merged